CREATE TABLE IF NOT EXISTS public.topics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  total_sources INTEGER DEFAULT 0,
  last_updated TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.timeline_entries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  topic_id UUID NOT NULL REFERENCES public.topics(id) ON DELETE CASCADE,
  headline TEXT NOT NULL,
  excerpt TEXT NOT NULL,
  full_excerpt TEXT,
  source_name TEXT NOT NULL,
  source_logo_url TEXT,
  source_url TEXT NOT NULL,
  author TEXT,
  is_verified BOOLEAN DEFAULT false,
  tags TEXT[] DEFAULT '{}',
  published_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_timeline_entries_topic_id ON public.timeline_entries(topic_id);
CREATE INDEX IF NOT EXISTS idx_timeline_entries_published_at ON public.timeline_entries(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_topics_slug ON public.topics(slug);

ALTER TABLE public.topics REPLICA IDENTITY FULL;
ALTER TABLE public.timeline_entries REPLICA IDENTITY FULL;

INSERT INTO public.topics (id, title, summary, slug, total_sources, last_updated) VALUES
  ('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Global AI Regulation Summit 2024', 'World leaders and tech executives converge to establish international frameworks for artificial intelligence governance, addressing safety standards, ethical deployment, and cross-border data policies.', 'global-ai-regulation-summit-2024', 8, NOW()),
  ('b2c3d4e5-f6a7-8901-bcde-f12345678901', 'Mars Colony Mission: First Crew Selection', 'Space agencies announce the final crew selection for humanity''s first permanent Mars settlement, marking a historic milestone in interplanetary colonization efforts.', 'mars-colony-first-crew-selection', 6, NOW() - INTERVAL '2 hours'),
  ('c3d4e5f6-a7b8-9012-cdef-123456789012', 'Global Ocean Cleanup Breakthrough', 'Scientists unveil a revolutionary biodegradable nanomaterial that can neutralize microplastics in ocean water, promising to accelerate marine ecosystem recovery worldwide.', 'global-ocean-cleanup-breakthrough', 7, NOW() - INTERVAL '5 hours');

INSERT INTO public.timeline_entries (topic_id, headline, excerpt, full_excerpt, source_name, source_logo_url, source_url, author, is_verified, tags, published_at) VALUES
  ('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'EU Proposes Mandatory AI Safety Certifications', 'The European Union has unveiled a comprehensive proposal requiring all AI systems operating within member states to obtain safety certifications before deployment.', 'The European Union has unveiled a comprehensive proposal requiring all AI systems operating within member states to obtain safety certifications before deployment. The framework would establish tiered risk categories, with high-risk applications in healthcare, finance, and law enforcement facing the strictest requirements. Industry leaders have expressed mixed reactions, with some praising the clarity while others warn of stifled innovation.', 'Reuters', NULL, 'https://reuters.com', 'Maria Santos', true, ARRAY['AI', 'regulation', 'EU'], NOW() - INTERVAL '30 minutes'),

  ('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Tech Giants Form Self-Regulation Alliance', 'Leading technology companies including major AI developers have announced a voluntary self-regulation coalition ahead of the summit.', 'Leading technology companies including major AI developers have announced a voluntary self-regulation coalition ahead of the summit. The alliance commits to transparency reports, third-party safety audits, and shared incident databases. Critics argue self-regulation has historically failed in the tech sector, while proponents say it demonstrates industry willingness to cooperate with governments.', 'The New York Times', NULL, 'https://nytimes.com', 'James Chen', true, ARRAY['AI', 'tech', 'self-regulation'], NOW() - INTERVAL '2 hours'),

  ('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'China Announces Parallel AI Governance Framework', 'Beijing has released its own comprehensive AI governance plan, signaling potential divergence from Western regulatory approaches.', 'Beijing has released its own comprehensive AI governance plan, signaling potential divergence from Western regulatory approaches. The framework emphasizes state oversight and data sovereignty while promoting domestic AI innovation. Analysts see this as a strategic move to maintain competitive advantage while appearing cooperative on global governance.', 'BBC News', NULL, 'https://bbc.com', 'Li Wei', true, ARRAY['AI', 'China', 'governance'], NOW() - INTERVAL '4 hours'),

  ('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'AI Safety Researchers Warn of Regulatory Gaps', 'A coalition of 200+ AI safety researchers published an open letter highlighting critical gaps in proposed global regulation frameworks.', 'A coalition of 200+ AI safety researchers published an open letter highlighting critical gaps in proposed global regulation frameworks. The letter specifically addresses concerns about open-source AI models, autonomous weapons systems, and the rapid pace of capability advancement outstripping regulatory responses. The researchers call for mandatory pre-deployment testing protocols.', 'The Guardian', NULL, 'https://theguardian.com', 'Dr. Sarah Mitchell', true, ARRAY['AI safety', 'research', 'open letter'], NOW() - INTERVAL '6 hours'),

  ('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Developing Nations Demand Inclusive AI Policies', 'Representatives from 40+ developing nations issue joint statement demanding equitable representation in AI governance decisions.', 'Representatives from 40+ developing nations issue joint statement demanding equitable representation in AI governance decisions. The coalition argues that current proposals disproportionately favor wealthy nations and could create technological dependencies. They advocate for technology transfer agreements and capacity-building provisions in any global framework.', 'Al Jazeera', NULL, 'https://aljazeera.com', 'Amira Hassan', true, ARRAY['AI', 'developing nations', 'equity'], NOW() - INTERVAL '8 hours'),

  ('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Leaked Draft Reveals Contentious Summit Provisions', 'An unverified leaked document appears to show controversial provisions in the draft summit agreement, including surveillance exceptions.', 'An unverified leaked document appears to show controversial provisions in the draft summit agreement, including surveillance exceptions for national security purposes and weakened penalties for non-compliance. The authenticity of the document has not been confirmed by organizers, but it has sparked intense debate among policy experts and civil liberties organizations.', 'TechInsider Blog', NULL, 'https://techinsiderblog.example.com', 'Anonymous', false, ARRAY['AI', 'leak', 'controversy'], NOW() - INTERVAL '10 hours'),

  ('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Silicon Valley Startups Fear Compliance Burden', 'Small AI startups voice concerns that proposed regulations could create prohibitive compliance costs, potentially crushing innovation.', 'Small AI startups voice concerns that proposed regulations could create prohibitive compliance costs, potentially crushing innovation in the sector. A survey of 150 AI startups found that 73% believe the proposed certification requirements would require resources beyond their current capacity. Venture capital firms are reportedly reassessing AI investments pending regulatory clarity.', 'Wired', NULL, 'https://wired.com', 'Alex Kumar', true, ARRAY['AI', 'startups', 'compliance'], NOW() - INTERVAL '12 hours'),

  ('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Insider Claims Summit Agreement Already Decided', 'An anonymous source claiming to be close to negotiations says major points have already been secretly agreed upon by leading nations.', 'An anonymous source claiming to be close to negotiations says major points have already been secretly agreed upon by leading nations before the official summit begins. The claims suggest backroom deals on enforcement mechanisms and exemptions for military AI applications. No official confirmation has been provided and several delegations have denied the allegations.', 'The Daily Wire Report', NULL, 'https://dailywirereport.example.com', 'Unknown', false, ARRAY['AI', 'summit', 'rumor'], NOW() - INTERVAL '14 hours'),

  ('b2c3d4e5-f6a7-8901-bcde-f12345678901', 'NASA Announces Final 12 Candidates for Mars Mission', 'After years of rigorous selection, NASA has revealed the 12 astronauts who will form the first permanent Mars settlement crew.', 'After years of rigorous selection, NASA has revealed the 12 astronauts who will form the first permanent Mars settlement crew. The diverse team includes engineers, biologists, geologists, and medical professionals from 8 different countries. Training will begin immediately at a newly constructed Mars simulation facility in the Nevada desert.', 'NASA Official', NULL, 'https://nasa.gov', 'Dr. Katherine Reyes', true, ARRAY['Mars', 'NASA', 'space'], NOW() - INTERVAL '1 hour'),

  ('b2c3d4e5-f6a7-8901-bcde-f12345678901', 'SpaceX Confirms Starship Ready for Mars Transit', 'Elon Musk''s SpaceX has confirmed that the latest Starship variant has passed all critical tests for the Mars transit mission.', 'Elon Musk''s SpaceX has confirmed that the latest Starship variant has passed all critical tests for the Mars transit mission. The vehicle features enhanced radiation shielding, a closed-loop life support system, and artificial gravity modules for the 7-month journey. Launch is tentatively scheduled for the next optimal transfer window.', 'Associated Press', NULL, 'https://apnews.com', 'Robert Chang', true, ARRAY['Mars', 'SpaceX', 'Starship'], NOW() - INTERVAL '3 hours'),

  ('b2c3d4e5-f6a7-8901-bcde-f12345678901', 'Medical Experts Raise Health Concerns for Crew', 'Leading space medicine researchers highlight unprecedented health risks facing the Mars crew during the extended mission.', 'Leading space medicine researchers highlight unprecedented health risks facing the Mars crew during the extended mission. Concerns include prolonged radiation exposure, bone density loss, psychological isolation effects, and the challenges of performing emergency medical procedures with limited resources. New countermeasures have been developed but remain largely untested in deep space conditions.', 'The Lancet', NULL, 'https://thelancet.com', 'Dr. James Morrison', true, ARRAY['Mars', 'health', 'medicine'], NOW() - INTERVAL '5 hours'),

  ('b2c3d4e5-f6a7-8901-bcde-f12345678901', 'Russia Disputes Crew Selection Process', 'Russian space agency Roscosmos has formally protested the crew selection, claiming their cosmonauts were unfairly excluded.', 'Russian space agency Roscosmos has formally protested the crew selection, claiming their cosmonauts were unfairly excluded from the final roster. The dispute threatens international cooperation on the mission and could affect resupply logistics. Diplomatic negotiations are underway to resolve the disagreement before the training phase begins.', 'RT News', NULL, 'https://rt.com', 'Dmitri Volkov', false, ARRAY['Mars', 'Russia', 'dispute'], NOW() - INTERVAL '7 hours'),

  ('b2c3d4e5-f6a7-8901-bcde-f12345678901', 'Private Investors Pledge $50B for Mars Infrastructure', 'A consortium of private investors has committed $50 billion toward Mars colony infrastructure development.', 'A consortium of private investors has committed $50 billion toward Mars colony infrastructure development, including habitat construction, resource extraction equipment, and communication relays. The investment marks the largest private space funding commitment in history and signals growing commercial interest in Mars colonization.', 'Financial Times', NULL, 'https://ft.com', 'Emma Blackwell', true, ARRAY['Mars', 'investment', 'infrastructure'], NOW() - INTERVAL '9 hours'),

  ('b2c3d4e5-f6a7-8901-bcde-f12345678901', 'Conspiracy Theories Emerge Around Mars Mission', 'Social media platforms are seeing a surge in conspiracy theories claiming the Mars mission is a cover for secret military operations.', 'Social media platforms are seeing a surge in conspiracy theories claiming the Mars mission is a cover for secret military operations in orbit. Despite no evidence supporting these claims, they have gained significant traction online, prompting NASA to issue multiple clarifications. Experts warn that disinformation could undermine public support for the historic mission.', 'InfoWars Daily', NULL, 'https://infowars.example.com', 'Unknown', false, ARRAY['Mars', 'conspiracy', 'disinformation'], NOW() - INTERVAL '11 hours'),

  ('c3d4e5f6-a7b8-9012-cdef-123456789012', 'Scientists Unveil Nanomaterial That Neutralizes Microplastics', 'A breakthrough biodegradable nanomaterial developed by MIT researchers can break down microplastics in ocean water within hours.', 'A breakthrough biodegradable nanomaterial developed by MIT researchers can break down microplastics in ocean water within hours. The material works by bonding with plastic polymer chains and accelerating their decomposition into harmless organic compounds. Initial ocean trials in the Pacific have shown 94% microplastic reduction in treated areas.', 'Nature', NULL, 'https://nature.com', 'Dr. Elena Rodriguez', true, ARRAY['ocean', 'microplastics', 'science'], NOW() - INTERVAL '2 hours'),

  ('c3d4e5f6-a7b8-9012-cdef-123456789012', 'UN Backs Global Deployment of Ocean Cleanup Technology', 'The United Nations Environment Programme has endorsed rapid deployment of the new nanomaterial across major ocean pollution zones.', 'The United Nations Environment Programme has endorsed rapid deployment of the new nanomaterial across major ocean pollution zones. A $2 billion emergency fund has been proposed to accelerate production and distribution. Environmental groups largely welcome the development but caution against viewing it as a substitute for reducing plastic production.', 'BBC News', NULL, 'https://bbc.com', 'Sarah Whitfield', true, ARRAY['ocean', 'UN', 'cleanup'], NOW() - INTERVAL '4 hours'),

  ('c3d4e5f6-a7b8-9012-cdef-123456789012', 'Fishing Industry Reports Marine Life Recovery', 'Commercial fishing operators in treated Pacific zones report unprecedented recovery in fish populations and marine biodiversity.', 'Commercial fishing operators in treated Pacific zones report unprecedented recovery in fish populations and marine biodiversity. Scientists attribute the rapid recovery to the elimination of microplastics from the food chain, allowing marine organisms to reproduce more successfully. The economic impact on fishing communities could reach billions of dollars annually.', 'Reuters', NULL, 'https://reuters.com', 'Michael Torres', true, ARRAY['ocean', 'fishing', 'recovery'], NOW() - INTERVAL '6 hours'),

  ('c3d4e5f6-a7b8-9012-cdef-123456789012', 'Environmental Group Questions Long-Term Safety', 'Greenpeace releases report raising concerns about unknown long-term effects of deploying nanomaterials at scale in marine environments.', 'Greenpeace releases report raising concerns about unknown long-term effects of deploying nanomaterials at scale in marine environments. While acknowledging the promising results, the organization calls for comprehensive environmental impact assessments before any large-scale deployment. The report highlights potential risks to coral reefs and deep-sea ecosystems.', 'The Guardian', NULL, 'https://theguardian.com', 'David Park', true, ARRAY['ocean', 'Greenpeace', 'safety'], NOW() - INTERVAL '8 hours'),

  ('c3d4e5f6-a7b8-9012-cdef-123456789012', 'Plastic Industry Lobbyists Attempt to Discredit Research', 'Leaked emails reveal coordinated efforts by plastic industry groups to cast doubt on the nanomaterial''s effectiveness.', 'Leaked emails reveal coordinated efforts by plastic industry groups to cast doubt on the nanomaterial''s effectiveness and safety. The campaign includes funding counter-studies and social media influence operations. Researchers behind the breakthrough have dismissed the attacks as financially motivated and stand by their peer-reviewed findings.', 'Investigative Post', NULL, 'https://investigativepost.example.com', 'Anon Reporter', false, ARRAY['ocean', 'lobbying', 'plastic industry'], NOW() - INTERVAL '10 hours'),

  ('c3d4e5f6-a7b8-9012-cdef-123456789012', 'Tech Startup Claims Superior Alternative Solution', 'An unverified tech startup claims to have developed an even more effective ocean cleanup solution but has yet to publish any scientific data.', 'An unverified tech startup claims to have developed an even more effective ocean cleanup solution using AI-guided drone swarms, but has yet to publish any scientific data or undergo peer review. The company has raised $100M in funding based on marketing materials alone. Scientists urge caution and demand transparent evidence before any claims of superiority.', 'TechBuzz Weekly', NULL, 'https://techbuzzweekly.example.com', 'Jordan Blake', false, ARRAY['ocean', 'startup', 'unverified'], NOW() - INTERVAL '12 hours'),

  ('c3d4e5f6-a7b8-9012-cdef-123456789012', 'Pacific Island Nations Celebrate Breakthrough', 'Leaders of Pacific Island nations, among the most affected by ocean pollution, express hope and gratitude for the scientific advancement.', 'Leaders of Pacific Island nations, among the most affected by ocean pollution, express hope and gratitude for the scientific advancement. Several nations have already committed to partnering with research teams for local deployment trials. The development is seen as a lifeline for communities whose livelihoods depend entirely on healthy marine ecosystems.', 'Associated Press', NULL, 'https://apnews.com', 'Lani Maka', true, ARRAY['ocean', 'Pacific Islands', 'celebration'], NOW() - INTERVAL '14 hours');

UPDATE public.topics SET total_sources = (
  SELECT COUNT(*) FROM public.timeline_entries WHERE topic_id = topics.id
);
